# Generated by Django 6.1.1 on 2026-09-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('fono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.TextField()),
                ('color', models.TextField()),
                ('sabor', models.TextField()),
                ('precio', models.PositiveIntegerField()),
                ('oferta', models.BooleanField()),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
    ]
